name: 'Documentaion build'
description: 'Converts markdown files using MkDocs to a versionized GitHub Pages documentation using mike'
inputs:
  github-token:
    description: 'Github token'
    required: true
  version:
    description: 'Version'
    required: true
  alias:
    description: 'Creates a symbolic link with that name to the page'
    required: false
  versionDiscoveryPageLocation:
    description: 'Location of the version discovery page (directory)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install mkdocs and plugins
      shell: bash
      run: |
        pip install mike mkdocs mkdocs-material mkdocs-drawio-file mkdocs-mermaid2-plugin

    - name: Setup user
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Deploy versionized documentation
      shell: bash
      run: |
        mike deploy --update-aliases --push ${{ inputs.version }} ${{ inputs.alias }}

    - name: Deploy version discovery page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ${{ inputs.versionDiscoveryPageLocation }}
        keep_files: true
