name: 'Documentaion build'
description: 'Converts markdown files using MkDocs to a versionized GitHub Pages documentation using mike'
inputs:
  github-token:
    description: 'Github token'
    required: true
  version:
    description: 'Version'
    required: true
  alias:
    description: 'Creates a symbolic link with that name to the page'
    required: false
  versionDiscoveryPageLocation:
    description: 'Location of the version discovery page (directory)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        pip install mkdocs-material
        pip install mike

    - name: Setup user
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Deploy versionized documentation
      shell: bash
      run: |
        mike deploy ${{ inputs.version }} ${{ inputs.alias }} --push

    - name: Deploy version discovery page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ${{ inputs.versionDiscoveryPageLocation }}
        keep_files: true
